### PR TITLE
Introduce X509CertValidator and PrivateKeyValidator

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Had to use

```php
if (\ipl\I18n\StaticTranslator::$instance === null) {
    class Lolcat {
        public function translate($msg) {
            return $msg;
        }
    }
    \ipl\I18n\StaticTranslator::$instance = new Lolcat();
}
```

for testing.

What ensures `StaticTranslator::$instance` initialization?

**Comment by nilmerg** [comment]
For Web envs, the framework using this library. (e.g. Icinga Web 2)

For tests, [the test](https://github.com/Icinga/ipl-i18n/blob/translate-functions/tests/FunctionsTest.php#L15).

**Review by nilmerg — CHANGES_REQUESTED** [review]
Please add unit tests

**Review by nilmerg — APPROVED** [review]
Thank you!

**Pull request merged**
